### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: spawnSync openssl ENOENT

### ISSUE THREAD

**Issue by laurensmartz** [pnp/contoso#6]
(node:20764) UnhandledPromiseRejectionWarning: Error: spawnSync openssl ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.WriteLocalSSLCerts (C:\www\foxit\MarkDownFileHandler\filehandler\tools\local-setup\tasks\create-ssl-files.js:12:21)
    at Object.<anonymous> (C:\www\foxit\MarkDownFileHandler\filehandler\tools\local-setup\index.js:85:29)
    at step (C:\www\foxit\MarkDownFileHandler\filehandler\tools\local-setup\index.js:33:23)
    at Object.next (C:\www\foxit\MarkDownFileHandler\filehandler\tools\local-setup\index.js:14:53)
    at fulfilled (C:\www\foxit\MarkDownFileHandler\filehandler\tools\local-setup\index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by laurensmartz** [comment]
how to fix this problem?
